### ISSUE TITLE
AttributeError: 'DiceTensorFlow1' object has no attribute 'num_ouput_nodes'`

### ISSUE THREAD

**Issue by hobbitlzy** [interpretml/DiCE#149]
Traceback (most recent call last):
  File "G:/nus/Deep_explanation/Dice_baseline.py", line 22, in <module>
    dice_exp = exp.generate_counterfactuals(query_instance, total_CFs=4, desired_class="opposite")
  File "F:\Anaconda\lib\site-packages\dice_ml\explainer_interfaces\dice_tensorflow1.py", line 139, in generate_counterfactuals
    self.do_loss_initializations(yloss_type, diversity_loss_type, feature_weights)
  File "F:\Anaconda\lib\site-packages\dice_ml\explainer_interfaces\dice_tensorflow1.py", line 336, in do_loss_initializations
    self.yloss = self.compute_yloss(self.yloss_type)
  File "F:\Anaconda\lib\site-packages\dice_ml\explainer_interfaces\dice_tensorflow1.py", line 250, in compute_yloss
    temp_logits = temp_logits[:, (self.num_ouput_nodes-1):]
AttributeError: 'DiceTensorFlow1' object has no attribute 'num_ouput_nodes'

When I run the example codes in the readme, this error occurs. I dive into the source code of class "DiceTensorFlow1" and its father class "ExplainerBase". They indeed do not have this attribute.

**Comment by gaugup** [comment]
@hobbitlzy, could you take a look at https://github.com/interpretml/DiCE/issues/129. The error above looks similar to this issue. 

if you are using tensorflow, then need to set the backend to TF1 (for tensorflow v1) or TF2.

m = dice_ml.Model(model=ann_model,backend='TF1').

Can you share the sample code that you executed and ran into the above error?

**Comment by gaugup** [comment]
@hobbitlzy are you unblocked on this issue? If so, kindly close this issue.

**Comment by hobbitlzy** [comment]
Although I still do not know the problem when I use TF1, I moved to TF2 backend and it works.
