### ISSUE TITLE
generate_counterfactuals call results in error on Tensorflow v2.9

### ISSUE THREAD

**Issue by nagainfosolutions** [interpretml/DiCE#332]
Hello,

We recently updated to Tensorflow v2.9. Since the upgrade, we've had trouble with the _generate_counterfactuals_ function call. Below is my code and error. Note: The same code was working on Tensorflow 1.x.

```
import numpy as np
import pandas as pd
import tensorflow as tf

dataset = pd.read_csv('data_NN_for_classification_binary.csv')

categorical_names = ['Geography','Gender']
target_name = ['Exited']

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore')
encoded_df = pd.DataFrame(encoder.fit_transform(dataset[categorical_names]).toarray())
encoded_df.columns = encoder.get_feature_names(categorical_names)
dataset = pd.concat([dataset,encoded_df], axis='columns')
dataset = dataset.drop(categorical_names, axis='columns')
encoded_df = None

target_df = dataset[target_name]
dataset = dataset.drop(target_name, axis='columns')
dataset = pd.concat([dataset,target_df], axis='columns')
target_df = None

features = dataset.columns.values[:-1]

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
class_names = dataset["Exited"].unique()

from keras.utils import np_utils
y = np_utils.to_categorical(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

import keras 
from keras.models import Sequential 
from keras.layers import Dense
from keras.models import model_from_json

ann = Sequential()

ann.add(Dense(units = len(features), kernel_initializer = 'uniform', activation = 'relu'))

ann.add(Dense(units = 12, kernel_initializer = 'uniform', activation = 'relu'))

ann.add(Dense(units = 2, kernel_initializer = 'uniform', activation = 'softmax')) 

ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

ann.fit(X_train, y_train, batch_size = 32, epochs = 10)

y_pred = ann.predict (X_test[0:1])

import dice_ml
dice_data = dice_ml.Data(dataframe=dataset, 
                         continuous_features = features.tolist(), 
                         outcome_name = 'Exited')

dice_model = dice_ml.Model(model=ann, 
                           backend="TF2")

dice_explainer = dice_ml.Dice(dice_data, 
                        dice_model, 
                        method="random")

query_instance = {'CreditScore':714,
                'Age':45,
                'Tenure':8,
                'Balance':150900,
                'NumOfProducts':2,
                'HasCrCard': 0,
                'IsActiveMember':1,
                'EstimatedSalary': 139889,
                'Geography_France': 0,
                'Geography_Germany': 0,
                'Geography_Spain': 1,
                'Gender_Female': 0,
                'Gender_Male': 1}

counterfactuals = dice_explainer.generate_counterfactuals(query_instance, 
                                       total_CFs = 1, 
                                       desired_class = 'opposite',
                                       features_to_vary=['CreditScore', 'Tenure', 'EstimatedSalary'],
                                       permitted_range={'CreditScore': [400, 800],
                                                        'Tenure': [1, 7], 
                                                        'EstimatedSalary': [5000, 999999]})

counterfactuals.visualize_as_dataframe(show_only_changes=True)
```

Executing this results in the following error from the generate_counterfactuals function call

```
Traceback (most recent call last):

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "d:\my files\dice\ai\code\sample\dice_test\dice_test.py", line 188, in <module>
    counterfactuals = dice_explainer.generate_counterfactuals(query_instance,

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\dice_ml\explainer_interfaces\dice_tensorflow2.py", line 117, in generate_counterfactuals
    self.minx, self.maxx = self.data_interface.get_minx_maxx(normalized=True)

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\dice_ml\data_interfaces\public_data_interface.py", line 302, in get_minx_maxx
    minx[0][idx] = (self.permitted_range[feature_name]

KeyError: 'Age'
```

Age is not one of the features we expect dice to vary. Again, we never had this issue with an older version of TF.

**Comment by nagainfosolutions** [comment]
I'd like to add that if I remove the line specifying _permitted_range_, that is if I change the _generate_counterfactuals_ line to below

```
counterfactuals = dice_explainer.generate_counterfactuals(query_instance, 
                                       total_CFs = 2, 
                                       desired_class = 'opposite',
                                       features_to_vary=['CreditScore', 'Tenure', 'EstimatedSalary'])
```

then the execution is initiated, but after several seconds I receive the error

```
Traceback (most recent call last):

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "d:\my files\dice\ai\code\sample\dice_test\dice_test.py", line 188, in <module>
    counterfactuals = dice_explainer.generate_counterfactuals(query_instance,

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\dice_ml\explainer_interfaces\dice_tensorflow2.py", line 132, in generate_counterfactuals
    self.find_counterfactuals(query_instance, desired_class, optimizer,

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\dice_ml\explainer_interfaces\dice_tensorflow2.py", line 567, in find_counterfactuals
    final_cfs_df_sparse = self.do_posthoc_sparsity_enhancement(

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\dice_ml\explainer_interfaces\explainer_base.py", line 537, in do_posthoc_sparsity_enhancement
    final_cfs_sparse = self.do_linear_search(diff, decimal_prec, query_instance, cf_ix,

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\dice_ml\explainer_interfaces\explainer_base.py", line 559, in do_linear_search
    while((abs(diff) > 10e-4) and (np.sign(diff*old_diff) > 0) and self.is_cf_valid(current_pred)):

  File "C:\Users\test\.conda\envs\dice-env\lib\site-packages\dice_ml\explainer_interfaces\explainer_base.py", line 724, in is_cf_valid
    pred_1 = model_score[self.num_output_nodes-1]

IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by amit-sharma** [comment]
@nagainfosolutions the tensorflow code was updated in the latest version v0.9. Can you try using the latest version from pip? Let me know if the error still persists.

**Comment by nagainfosolutions** [comment]
This issue is fixed now. Thank you for the quick resolution. Much appreciated.
